### PR TITLE
Corrects little typo in README.md

### PR DESCRIPTION
**Pull request by abevieiramota**

### CODE REVIEW

**Comment by rjuju** [comment]
Thanks a lot :)

**Comment by mohanpatil048** [comment]
pg_sortstats.c: In function ‘pgsrt_process_sortstate’:
pg_sortstats.c:1620:56: error: ‘PlanState’ has no member named ‘scandesc’
  tuple_palloc += get_alignment_overhead(srtstate->ss.ps.scandesc);


I guess 'scandesc' is not declared. 
Contributor plz look into this.

Thanks,
Patil Mohan

**Comment by rjuju** [comment]
@mohanpatil048 Thanks a lot for the report!  I just pushed some fixes, the extension should compile on all version from 9.4 to 12.
